### ISSUE TITLE
Test minimum bid functionality

### ISSUE THREAD

**Issue by silviya-v00** [boiche/AuctionSystem#11]
Execution steps:
- Step 1: Insert positive number (ex: 200)
- Step 2: Insert negative number (ex: -200)
- Step 3: No number inserted
- Step 4: A try with 100 as bid

Expected results:
- Unaccepted bid when minimum bid is 200
- Accepted bid when minimum bid is -200 or left empty

**Comment by silviya-v00** [comment]
Unexpected result:
- Slow database connection
- No exception for current user's ID

**Comment by Imortalco** [comment]
Reason:
Forgot to change Data Source string in AuctionSystemContext.cs
